### ISSUE TITLE
module.exports = function(options={}) {

### ISSUE THREAD

**Issue by pfrlv** [whmountains/gulp-atomizer#13]
Hi )
What is it?
`module.exports = function(options={}) {`
And this...
`let {outfile, acssConfig, cssOptions, addRules} = options`

**Comment by whmountains** [comment]
It's ES2015 default parameters and destructuring.

`module.exports = function(options={}) {` Makes options have a default value of `{}` rather than `undefined`.

`let {outfile, acssConfig, cssOptions, addRules} = options` is equivalent to the following:
```
let outfile         = options.outfile
let acssConfig = options.acssConfig
let cssOptions = options.cssOptions
let addRules     = options.addRules
```
This article will explain more: https://ponyfoo.com/articles/es6-destructuring-in-depth

I wouldn't have used these "new-fangled" features for a browser-based module without a transpiler.  But these language features are already supported in the current LTS release of node so I have no problem using them there.
